//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2019LD601_PRACTICA0204
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public int id_productos { get; set; }
        public string nombre { get; set; }
        public Nullable<int> id_categorias { get; set; }
        public Nullable<double> precio { get; set; }
        public string estado { get; set; }
    
        public virtual Categoria Categoria { get; set; }
    }
}
